version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - Berkmann18
  assignees:
  - Berkmann18
  labels:
  - dependencies
  ignore:
  - dependency-name: webpack
    versions:
    - "> 4.28.2"
  - dependency-name: commander
    versions:
    - 6.2.1
    - 7.0.0
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
    - 4.4.0
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: "@babel/traverse"
    versions:
    - 7.12.12
  - dependency-name: elliptic
    versions:
    - 6.5.3
